import Link from 'next/link';
import { InquiryButton } from './inquiry-provider';
import { homeCategories, homeProducts, homeInsights, processSteps, journey, capabilities, type HomeImage } from '@/lib/homepage';
import styles from './homepage-sections.module.css';

function ImagePlaceholder({ image }: { image: HomeImage }) { return <div className={`${styles.placeholder} ${styles[`role-${image.role}`]}`} role="img" aria-label={image.alt}><span>CNL</span><small>{image.role.toUpperCase()} IMAGE</small></div>; }
export function HomepageHero() { return <section className={styles.hero}><div className={styles.heroCopy}><span className="eyebrow">BEAUTY OEM / ODM · PRIVATE LABEL</span><h1>From Market Opportunity to Market-Ready Products.</h1><p>We identify promising beauty opportunities and turn them into scalable skincare, body care and personal care products — from formula and packaging to production.</p><div className={styles.actions}><Link className="button button-dark" href="/start-your-project">Start Your Project</Link><Link className="button button-outline" href="/products">Explore Products →</Link></div><div className={styles.trustLine}><span>OEM / ODM</span><span>Flexible Customization</span><span>Global Market Support</span></div></div><ImagePlaceholder image={{ role: 'hero', alt: 'Beauty product development visual' }} /></section>; }
export function ProductSolutions() { return <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">PRODUCT SOLUTIONS</span><h2>Explore What We Can Build.</h2><p>Flexible OEM/ODM solutions across skincare, body care, hair care and personal care.</p></div><div className={styles.categoryMosaic}>{homeCategories.map(category => <Link href={`/products/${category.slug}`} className={`${styles.categoryTile} ${styles[category.layout]}`} key={category.slug}><ImagePlaceholder image={category.image}/><div><span>{category.name}</span><p>{category.groups.slice(0, 3).map(g => g.name).join(' · ')}</p><b>Explore →</b></div></Link>)}</div></div></section>; }
export function MarketOpportunities() { return <section className="section section-white"><div className="container"><div className="section-heading"><span className="eyebrow">MARKET OPPORTUNITIES</span><h2>What’s Next in Beauty.</h2><p>Product concepts shaped by market signals, category movement and real development opportunities.</p></div><div className={styles.productRail}>{homeProducts.map(product => <Link href={product.href} className={styles.productTile} key={product.href}><ImagePlaceholder image={product.image}/><span>{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><b>Explore Product →</b></Link>)}</div><Link className="button button-outline" href="/products">Explore Product Library →</Link></div></section>; }
export function IdeaToProduct() { return <section className="section section-muted"><div className={`container ${styles.split}`}><div><div className="section-heading"><span className="eyebrow">HOW WE WORK</span><h2>From Idea to Product.</h2><p>We identify market opportunities and transform them into scalable products.</p></div><div className={styles.process}>{processSteps.map(step => <div key={step[0]}><b>{step[0]}</b><span><strong>{step[1]}</strong><small>{step[2]}</small></span></div>)}</div><Link className="button button-outline" href="/how-we-work">How We Work →</Link></div><ImagePlaceholder image={{role:'process',alt:'Product development and packaging process'}}/></div></section>; }
export function SelectedProjects() { return <section className="section"><div className={`container ${styles.projects}`}><div><ImagePlaceholder image={{role:'project',alt:'Selected product project'}}/><span className="eyebrow">SELECTED PROJECTS</span><h2>Products We’ve Helped Bring to Life.</h2></div><div><ImagePlaceholder image={{role:'project',alt:'Product project'}}/><ImagePlaceholder image={{role:'project',alt:'Product project'}}/></div></div></section>; }
export function WhyCareNova() { return <section className="section section-dark"><div className={`container ${styles.why}`}><div className="section-heading"><span className="eyebrow">WHY CARENOVA LAB</span><h2>More Than Manufacturing.</h2><p>Product insight, development and manufacturing brought together in one workflow.</p></div><div className={styles.capabilities}>{capabilities.map(item => <div key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></div>)}</div></div></section>; }
export function Manufacturing() { return <section className="section section-white"><div className={`container ${styles.split}`}><ImagePlaceholder image={{role:'factory',alt:'Manufacturing and quality control'}}/><div className="section-heading"><span className="eyebrow">MANUFACTURING</span><h2>Built to Move from Sample to Scale.</h2><p>From formulation and sampling to filling, packing and quality control, we coordinate production around your product requirements.</p><div className={styles.capabilityList}>{['Formula Development','Sampling','Bulk Manufacturing','Filling & Packing','Quality Control','Export Documentation'].map(item => <span key={item}>{item}</span>)}</div><Link className="button button-outline" href="/solutions">Explore Our Capabilities →</Link></div></div></section>; }
export function TrustNumbers() { return <section className={styles.numbers}><div className="container">{[['7+','Years of beauty industry experience'],['—','Products developed'],['—','Markets supported'],['—','OEM / ODM projects']].map(x => <div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>; }
export function InsightsPreview() { return <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">BEAUTY INTELLIGENCE</span><h2>Insights for Building Better Products.</h2><p>Market trends, product development ideas and regulatory knowledge for beauty brands.</p></div><div className={styles.insights}>{homeInsights.map(article => <Link href={`/insights/${article.slug}`} key={article.slug}><ImagePlaceholder image={{role:'insight',alt:article.title}}/><span>{article.category}</span><h3>{article.title}</h3><p>{article.excerpt}</p><b>Read Insight →</b></Link>)}</div><Link className="button button-outline" href="/insights">View All Insights →</Link></div></section>; }
export function DevelopmentJourney() { return <section className="section section-muted"><div className="container"><div className="section-heading"><span className="eyebrow">YOUR DEVELOPMENT JOURNEY</span><h2>A Clear Path from Brief to Production.</h2></div><div className={styles.journey}>{journey.map((step, i) => <div key={step}><b>0{i + 1}</b><span>{step}</span>{i < journey.length - 1 && <i>→</i>}</div>)}</div></div></section>; }
export function HomepageRFQ() { return <section className="section"><div className={`container ${styles.rfq}`}><div><span className="eyebrow">START YOUR PROJECT</span><h2>Have a Product in Mind?</h2><p>Tell us what you want to develop. Our team will review your product, target market, quantity and customization requirements.</p><ul><li>Formula Development</li><li>Packaging Customization</li><li>OEM / ODM</li><li>Global Market Support</li></ul></div><div className={styles.rfqPanel}><h3>Start with a project brief</h3><p>Share your requirements with our product team.</p><InquiryButton>Submit Your Project →</InquiryButton><Link className="text-link" href="/start-your-project">Complete the full brief →</Link></div></div></section>; }
export function FloatingInquiry() { return <div className={styles.floating}><InquiryButton>✉ <span>Talk to Us</span></InquiryButton></div>; }
