import Link from 'next/link';
import { homeCategories, homeProducts, homeInsights, journey, capabilities, type HomeImage } from '@/lib/homepage';
import styles from './homepage-sections.module.css';
import { HomepageInquiryDrawer } from './homepage-inquiry-drawer';

function ImagePlaceholder({ image }: { image: HomeImage }) { return <div className={`${styles.placeholder} ${styles[`role-${image.role}`]}`} role="img" aria-label={image.alt}><span>CNL</span><small>{image.role.toUpperCase()} IMAGE</small></div>; }
export function HomepageHero() { return <section className={styles.hero}><ImagePlaceholder image={{ role: 'hero', alt: 'Premium skincare, packaging, formula samples and product development visual' }} /><div className={styles.heroOverlay}/><div className={`container ${styles.heroContent}`}><div className={styles.heroCopy}><span className="eyebrow">FROM MARKET INSIGHT TO PRODUCT</span><h1>From Market Opportunity to Market-Ready Products.</h1><p>We identify market opportunities and turn them into scalable skincare, personal care and beauty products — from concept and formulation to packaging and manufacturing.</p><div className={styles.heroTags}>SKINCARE · PERSONAL CARE · OEM/ODM · PRIVATE LABEL · PRODUCT DEVELOPMENT</div><div className={styles.actions}><Link className="button button-dark" href="/start-your-project">Start Your Project →</Link><Link className="button button-outline" href="/products">Explore Products →</Link></div></div></div></section>; }
export function ProductSolutions() { return <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">PRODUCT SOLUTIONS</span><h2>Explore What We Can Build.</h2><p>Explore scalable product directions across the categories shaping today’s beauty market.</p></div><div className={styles.categoryMosaic}>{homeCategories.map(category => <Link href={`/products/${category.slug}`} className={`${styles.categoryTile} ${styles[category.layout]}`} key={category.slug}><ImagePlaceholder image={category.image}/><div><span>{category.name}</span><p>{category.groups.slice(0, 3).map(g => g.name).join(' · ')}</p><b>Explore Products →</b></div></Link>)}</div></div></section>; }
export function MarketOpportunities() { return <section className="section section-white"><div className="container"><div className="section-heading"><span className="eyebrow">MARKET OPPORTUNITIES</span><h2>What’s Next in Beauty.</h2><p>Trend-led product concepts selected around emerging consumer demand and private-label opportunities.</p></div><div className={styles.trendGrid}>{homeProducts.map((product, i) => <Link href={product.href} className={`${styles.productTile} ${i === 0 ? styles.trendFeatured : ''}`} key={product.href}><ImagePlaceholder image={product.image}/><span>{i === 0 ? 'FEATURED OPPORTUNITY' : 'TREND / OPPORTUNITY'}</span><h3>{product.name}</h3><p>{product.description}</p><b>Explore Concept →</b></Link>)}</div><Link className="button button-outline" href="/products">Explore Product Library →</Link></div></section>; }
export function IdeaToProduct() { return <section className="section section-muted"><div className={`container ${styles.split}`}><div><div className="section-heading"><span className="eyebrow">PRODUCT DEVELOPMENT</span><h2>From Idea to Product.</h2><p>From market signal to a workable product direction, we coordinate the decisions that move a concept forward.</p></div><div className={styles.process}>{[['01','Market & Trend Research','Identify the opportunity.'],['02','Product Strategy','Define the right direction.'],['03','Formula Development','Build for target-market needs.'],['04','Packaging & Sampling','Make the concept tangible.'],['05','Compliance Support','Prepare for launch requirements.'],['06','Manufacturing & Delivery','Move from sample to scale.']].map(step => <div key={step[0]}><b>{step[0]}</b><span><strong>{step[1]}</strong><small>{step[2]}</small></span></div>)}</div><Link className="button button-outline" href="/how-we-work">How We Work →</Link></div><ImagePlaceholder image={{role:'process',alt:'Formula samples, packaging development and product design process'}}/></div></section>; }
export function SelectedProjects() { return <section className="section"><div className={`container ${styles.projects}`}><div><ImagePlaceholder image={{role:'project',alt:'Selected product project'}}/><span className="eyebrow">SELECTED PROJECTS</span><h2>Products We’ve Helped Bring to Life.</h2></div><div><ImagePlaceholder image={{role:'project',alt:'Product project'}}/><ImagePlaceholder image={{role:'project',alt:'Product project'}}/></div></div></section>; }
export function WhyCareNova() { return <section className="section section-dark"><div className={`container ${styles.why}`}><div className="section-heading"><span className="eyebrow">WHY CARENOVA LAB</span><h2>More Than Manufacturing.</h2><p>Product insight, development and manufacturing brought together in one workflow.</p></div><div className={styles.capabilities}>{[['01','Market Insight','Identify emerging product opportunities.'],['02','Product Development','Turn ideas into scalable product concepts.'],['03','Compliance Support','Develop with target-market requirements in mind.'],['04','Manufacturing','Move efficiently from sample to production.']].map(item => <div key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></div>)}</div></div></section>; }
export function Manufacturing() { return <section className="section section-white"><div className={`container ${styles.split}`}><ImagePlaceholder image={{role:'factory',alt:'Manufacturing and quality control'}}/><div className="section-heading"><span className="eyebrow">CAPABILITIES</span><h2>Built to Move from Sample to Scale.</h2><p>Clear development options for brands moving from first brief to production.</p><div className={styles.specGrid}>{['MOQ · Flexible by project','Formula · Stock / Semi-Custom / Custom','Packaging · Bottle · Jar · Tube · Sachet','Sampling · Formula and packaging samples','OEM / ODM · Private label support','Markets · Global project coordination'].map(item => <span key={item}>{item}</span>)}</div><Link className="button button-outline" href="/solutions">Explore Our Capabilities →</Link></div></div></section>; }
export function TrustNumbers() { return <section className={styles.numbers}><div className="container">{[['7+','Years of beauty industry experience'],['—','Products developed'],['—','Markets supported'],['—','OEM / ODM projects']].map(x => <div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>; }
export function InsightsPreview() { return <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">BEAUTY INTELLIGENCE</span><h2>Insights for Building Better Products.</h2><p>Market trends, product development ideas and regulatory knowledge for beauty brands.</p></div><div className={styles.insights}>{homeInsights.map(article => <Link href={`/insights/${article.slug}`} key={article.slug}><ImagePlaceholder image={{role:'insight',alt:article.title}}/><span>{article.category}</span><h3>{article.title}</h3><p>{article.excerpt}</p><b>Read Insight →</b></Link>)}</div><Link className="button button-outline" href="/insights">View All Insights →</Link></div></section>; }
export function DevelopmentJourney() { return <section className="section section-muted"><div className="container"><div className="section-heading"><span className="eyebrow">YOUR DEVELOPMENT JOURNEY</span><h2>A Clear Path from Brief to Production.</h2></div><div className={styles.journey}>{journey.map((step, i) => <div key={step}><b>0{i + 1}</b><span>{step}</span>{i < journey.length - 1 && <i>→</i>}</div>)}</div></div></section>; }
export function HomepageRFQ() { return <section className={`section ${styles.finalCta}`}><div className={`container ${styles.rfq}`}><div><span className="eyebrow">START YOUR PROJECT</span><h2>Have a Product in Mind?</h2><p>Tell us what you want to develop. We'll help turn the brief into a workable product direction.</p><ul><li>Flexible by product & packaging</li><li>Stock / Semi-Custom / Custom</li><li>OEM · ODM · Private Label</li><li>Global project support</li></ul></div><div className={styles.rfqPanel}><h3>Start with a project brief</h3><p>Share your requirements with our product team.</p><HomepageInquiryDrawer triggerLabel="Start My Project →" /><Link className="text-link" href="/start-your-project">Complete the full brief →</Link></div></div></section>; }
export function FloatingInquiry() { return <HomepageInquiryDrawer floating triggerLabel="START A PROJECT  →" />; }
